import type { PracticeQuestionSeed } from "./types";

/**
 * Original MDCAT-syllabus practice MCQs (not sourced from any specific past
 * paper — authored fresh against the confirmed PMDC 2025 Uniform Curriculum,
 * targeting the 2027 exam cycle). Inserted as "pending" staging questions
 * for admin review before publishing — see seedPracticeQuestions.ts.
 *
 * Web-scraping real past papers for this batch proved unreliable (dead
 * official links, gated "share to unlock" content, scanned-image PDFs) —
 * see conversation notes. These are original questions instead, written to
 * FSc-level accuracy rather than transcribed from an unverifiable source.
 */
export const PRACTICE_QUESTIONS_SEED: PracticeQuestionSeed[] = [
  // ---- Biology ----
  {
    subject: "Biology",
    questionText: "Which cell organelle is chiefly responsible for producing ATP through aerobic cellular respiration?",
    optionA: "Golgi apparatus",
    optionB: "Mitochondria",
    optionC: "Lysosome",
    optionD: "Ribosome",
    correctOption: "B",
    explanation: "Mitochondria carry out oxidative phosphorylation to generate ATP, earning the nickname \"powerhouse of the cell.\"",
  },
  {
    subject: "Biology",
    questionText: "A competitive enzyme inhibitor works by:",
    optionA: "Binding to the active site and being overcome by higher substrate concentration",
    optionB: "Binding only to the enzyme-substrate complex",
    optionC: "Permanently denaturing the enzyme",
    optionD: "Increasing the enzyme's maximum reaction rate (Vmax)",
    correctOption: "A",
    explanation: "Competitive inhibitors resemble the substrate and compete for the active site, so raising substrate concentration can outcompete the inhibitor.",
  },
  {
    subject: "Biology",
    questionText: "Mendel's Law of Segregation states that:",
    optionA: "The two alleles for a gene separate during gamete formation so each gamete carries only one allele",
    optionB: "Genes for different traits assort independently of each other",
    optionC: "Alleles blend permanently in the offspring's phenotype",
    optionD: "Only dominant alleles are ever passed to offspring",
    correctOption: "A",
    explanation: "Segregation concerns a single gene's allele pair separating during meiosis; independent assortment (a separate law) concerns different genes.",
  },
  {
    subject: "Biology",
    questionText: "The semi-conservative model of DNA replication was experimentally confirmed by:",
    optionA: "Watson and Crick",
    optionB: "Meselson and Stahl",
    optionC: "Hershey and Chase",
    optionD: "Griffith",
    correctOption: "B",
    explanation: "Meselson and Stahl's 1958 density-gradient centrifugation experiment with ¹⁵N-labeled DNA confirmed semi-conservative replication.",
  },
  {
    subject: "Biology",
    questionText: "Which enzyme initiates protein digestion in the acidic environment of the stomach?",
    optionA: "Amylase",
    optionB: "Lipase",
    optionC: "Pepsin",
    optionD: "Trypsin",
    correctOption: "C",
    explanation: "Pepsin is active around pH 2 and begins breaking proteins into smaller peptides; trypsin acts later in the small intestine.",
  },
  {
    subject: "Biology",
    questionText: "A rightward shift of the oxygen-hemoglobin dissociation curve (as CO2 rises and pH falls in active tissue) means hemoglobin:",
    optionA: "Binds oxygen more tightly",
    optionB: "Releases oxygen more readily to the tissues",
    optionC: "Stops binding oxygen entirely",
    optionD: "Becomes permanently denatured",
    correctOption: "B",
    explanation: "This is the Bohr effect: lower pH and higher CO2 reduce hemoglobin's oxygen affinity, favoring oxygen release where tissues need it most.",
  },
  {
    subject: "Biology",
    questionText: "In the nephron, the majority of filtrate reabsorption (water, glucose, ions) occurs in the:",
    optionA: "Loop of Henle",
    optionB: "Proximal convoluted tubule",
    optionC: "Distal convoluted tubule",
    optionD: "Collecting duct",
    correctOption: "B",
    explanation: "Roughly 65-70% of filtered water, glucose, amino acids, and ions are reabsorbed in the proximal convoluted tubule.",
  },
  {
    subject: "Biology",
    questionText: "In a food chain, organisms that convert inorganic matter into organic matter using sunlight are classified as:",
    optionA: "Primary consumers",
    optionB: "Decomposers",
    optionC: "Producers",
    optionD: "Secondary consumers",
    correctOption: "C",
    explanation: "Producers (e.g., green plants, algae) are autotrophs that form the base of the food chain via photosynthesis.",
  },

  // ---- Chemistry ----
  {
    subject: "Chemistry",
    questionText: "Avogadro's number, representing the number of particles in one mole of a substance, is approximately:",
    optionA: "6.022 x 10^22",
    optionB: "6.022 x 10^23",
    optionC: "3.011 x 10^23",
    optionD: "1.66 x 10^-24",
    correctOption: "B",
  },
  {
    subject: "Chemistry",
    questionText: "A compound is 40% carbon, 6.7% hydrogen, and 53.3% oxygen by mass. Its empirical formula is:",
    optionA: "CH2O",
    optionB: "C2H4O2",
    optionC: "CH3O",
    optionD: "C2H6O",
    correctOption: "A",
    explanation: "Per 100 g: C = 40/12 ≈ 3.33 mol, H = 6.7/1 = 6.7 mol, O = 53.3/16 ≈ 3.33 mol. Dividing by the smallest (3.33) gives a 1:2:1 ratio — CH2O.",
  },
  {
    subject: "Chemistry",
    questionText: "Moving left to right across a period, atomic radius generally:",
    optionA: "Increases, due to increasing nuclear charge",
    optionB: "Decreases, due to increasing effective nuclear charge pulling electrons closer",
    optionC: "Stays essentially constant",
    optionD: "Increases, due to additional electron shells being added",
    correctOption: "B",
  },
  {
    subject: "Chemistry",
    questionText: "The hybridization of the carbon atom in methane (CH4) is:",
    optionA: "sp",
    optionB: "sp2",
    optionC: "sp3",
    optionD: "sp3d",
    correctOption: "C",
  },
  {
    subject: "Chemistry",
    questionText: "The functional group -OH attached to a carbon chain characterizes which class of organic compounds?",
    optionA: "Aldehydes",
    optionB: "Alcohols",
    optionC: "Carboxylic acids",
    optionD: "Ketones",
    correctOption: "B",
  },
  {
    subject: "Chemistry",
    questionText: "By Le Chatelier's principle, increasing pressure on a gaseous equilibrium shifts it toward the side with:",
    optionA: "More moles of gas",
    optionB: "Fewer moles of gas",
    optionC: "Equal moles, so no shift occurs",
    optionD: "No effect, since pressure never affects gaseous equilibria",
    correctOption: "B",
  },
  {
    subject: "Chemistry",
    questionText: "Which intermolecular force is primarily responsible for water's unusually high boiling point relative to its molar mass?",
    optionA: "London dispersion forces",
    optionB: "Dipole-dipole forces",
    optionC: "Hydrogen bonding",
    optionD: "Ionic bonding",
    correctOption: "C",
  },
  {
    subject: "Chemistry",
    questionText: "The oxidation state of sulfur in H2SO4 is:",
    optionA: "+4",
    optionB: "+6",
    optionC: "-2",
    optionD: "+2",
    correctOption: "B",
    explanation: "H is +1 (x2 = +2), O is -2 (x4 = -8). For the neutral molecule: +2 + S - 8 = 0, so S = +6.",
  },

  // ---- Physics ----
  {
    subject: "Physics",
    questionText: "A car accelerates uniformly from rest to 20 m/s in 5 seconds. Its acceleration is:",
    optionA: "2 m/s^2",
    optionB: "4 m/s^2",
    optionC: "5 m/s^2",
    optionD: "100 m/s^2",
    correctOption: "B",
    explanation: "a = (v - u) / t = (20 - 0) / 5 = 4 m/s^2.",
  },
  {
    subject: "Physics",
    questionText: "According to Newton's Second Law of Motion, force equals:",
    optionA: "Mass divided by acceleration",
    optionB: "Mass times velocity",
    optionC: "Mass times acceleration",
    optionD: "Mass times displacement",
    correctOption: "C",
  },
  {
    subject: "Physics",
    questionText: "Ohm's Law states that at constant temperature, the current through a conductor is:",
    optionA: "Inversely proportional to voltage",
    optionB: "Directly proportional to voltage and inversely proportional to resistance",
    optionC: "Independent of the applied voltage",
    optionD: "Directly proportional to resistance",
    correctOption: "B",
    explanation: "V = IR, so I = V/R: current increases with voltage and decreases as resistance increases.",
  },
  {
    subject: "Physics",
    questionText: "When two resistors are connected in series, the equivalent resistance is:",
    optionA: "Less than either individual resistance",
    optionB: "Equal to the smaller of the two resistances",
    optionC: "The sum of the individual resistances",
    optionD: "The product of the resistances divided by their sum",
    correctOption: "C",
  },
  {
    subject: "Physics",
    questionText: "The kinetic energy of an object of mass m moving with velocity v is given by:",
    optionA: "mv",
    optionB: "1/2 mv",
    optionC: "1/2 mv^2",
    optionD: "mv^2",
    correctOption: "C",
  },
  {
    subject: "Physics",
    questionText: "The half-life of a radioactive substance is the time required for:",
    optionA: "All the radioactive nuclei to decay",
    optionB: "Half of the radioactive nuclei to decay",
    optionC: "The substance's mass to double",
    optionD: "The substance to become stable in a single decay step",
    correctOption: "B",
  },
  {
    subject: "Physics",
    questionText: "In the photoelectric effect, electrons are emitted from a metal surface only when the incident light's frequency:",
    optionA: "Is below the metal's threshold frequency",
    optionB: "Is at or above the metal's threshold (work function) frequency",
    optionC: "Has no effect on whether electrons are emitted",
    optionD: "Equals zero",
    correctOption: "B",
  },
  {
    subject: "Physics",
    questionText: "A ball is thrown vertically upward. At the instant it reaches its maximum height, its:",
    optionA: "Velocity is zero, but its acceleration is still g, directed downward",
    optionB: "Velocity and acceleration are both zero",
    optionC: "Velocity is at its maximum",
    optionD: "Acceleration is zero",
    correctOption: "A",
    explanation: "Gravity continues to act throughout the flight; velocity momentarily reaches zero at the peak, but acceleration remains g downward.",
  },

  // ---- English ----
  {
    subject: "English",
    questionText: "Choose the word closest in meaning to \"Benevolent\":",
    optionA: "Cruel",
    optionB: "Kind",
    optionC: "Greedy",
    optionD: "Arrogant",
    correctOption: "B",
  },
  {
    subject: "English",
    questionText: "Choose the antonym of \"Scarce\":",
    optionA: "Rare",
    optionB: "Abundant",
    optionC: "Limited",
    optionD: "Insufficient",
    correctOption: "B",
  },
  {
    subject: "English",
    questionText: "Choose the word that means \"a doctor who specializes in diseases of the heart\":",
    optionA: "Neurologist",
    optionB: "Cardiologist",
    optionC: "Dermatologist",
    optionD: "Orthopedist",
    correctOption: "B",
  },
  {
    subject: "English",
    questionText: "Choose the grammatically correct sentence:",
    optionA: "Neither of the students have submitted their assignment.",
    optionB: "Neither of the students has submitted their assignment.",
    optionC: "Neither of the student have submit their assignment.",
    optionD: "Neither of the students has submit their assignment.",
    correctOption: "B",
    explanation: "\"Neither\" is grammatically singular and takes the singular verb \"has,\" even though it refers to a group.",
  },
  {
    subject: "English",
    questionText: "Fill in the blank: \"She is good ___ mathematics.\"",
    optionA: "in",
    optionB: "at",
    optionC: "on",
    optionD: "with",
    correctOption: "B",
    explanation: "\"Good at\" is the standard idiomatic preposition pairing for describing skill in a subject.",
  },
  {
    subject: "English",
    questionText: "Choose the correctly spelled word:",
    optionA: "Recieve",
    optionB: "Receive",
    optionC: "Receeve",
    optionD: "Receve",
    correctOption: "B",
    explanation: "\"i before e except after c\" — receive follows the \"except after c\" rule.",
  },
];
